### ISSUE TITLE
Missing GDPR Role

### ISSUE THREAD

**Issue by walkwizus** [magesuite/gdpr#2]
Hi,

This module can be install without any dependency ?

I dont see GPDR role in admin user view. All data are anonymized but I can't see customer information with an admin role but gpdr ACL are present.

Thanks !

**Comment by krisdante** [comment]
This module follows the rule of Privacy By default. That is why Super Admin will by default do not see private data. 
You need to create your own role(s), and instead of selecting "Access everywhere" in ACL, you need to manually decide about users' access that fits your business process. When you enable manual selection, you will be able to turn off one of the permissions called "Hide user data" in GDPR section. Users assigned to this role, later on, will be able to see private data. 
Super Admin by default has all the permission enabled and that includes "Hide user data".

If you need Super User that sees Private Data - create such a role, where everything is checked in access tree, except the hide checkbox.

**Comment by walkwizus** [comment]
Thanks, all works fine :).
